# -*- coding: utf-8 -*-
"""Retrieval_system.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16AfmPaJcVYKPEXdHEAJQQ2q1_sxvwhpQ
"""

from gensim import similarities


def search_docs(query, lsi, dictionary, corpus):
    vec_bow = dictionary.doc2bow(query.lower().split())
    vec_lsi = lsi[vec_bow]  # convert the query to LSI space
    vec_lsi = sorted(vec_lsi, key=lambda i: i[-1], reverse=True)
    print("\nvec_lsi\n", vec_lsi)
    index = similarities.MatrixSimilarity(lsi[corpus])  # transform corpus to LSI space and index it

    # index.save('/tmp/deerwester.index')
    # index = similarities.MatrixSimilarity.load('/tmp/deerwester.index')

    sims = index[vec_lsi]  # perform a similarity query against the corpus
    # print(list(enumerate(sims)))  # print (document_number, document_similarity) 2-tuples

    sims = sorted(enumerate(sims), key=lambda item: -item[1])
    
    return sims, vec_lsi